### PR TITLE
Update jruby-openssl to v0.9.7

### PR DESCRIPTION
**Pull request by jthurst01**
Update to support TLS1.1

### CODE REVIEW

**Comment by jadercorrea** [comment]
@freeformz I think we can merge this one. I'll take a look on version `0.9.12` and maybe open another PR later.

**Comment by freeformz** [comment]
You don't need this. You'll get the latest version when bundle installing. For instance when I bundle install this gem under jriuby-9.0.3.0 I get ...

```console
...
Installing jruby-openssl 0.9.12
...
```

**Comment by jadercorrea** [comment]
Yea, I was thinking of that after commenting. We should close this one.

**Comment by freeformz** [comment]
If you need a newer version you should do it in your app's Gemfile.

**Pull request closed without merging**
